### ISSUE TITLE
Unable to create task extending org.ysb33r.gradle.ivypot.OfflineRepositorySync

### ISSUE THREAD

**Issue by vojbarzz** [ysb33r/ivypot-gradle-plugin#20]
Hello,

I'm getting error `Unable to load class org.ysb33r.gradle.ivypot.OfflineRepositorySync due to missing dependency org/gradle/api/internal/DynamicObject` when trying to extend `OfflineRepositorySync` class using gradle 3.x. I have found that the solution would be to release a new version using gradle 3.x. Here is the source discussion https://discuss.gradle.org/t/missing-dependency-org-gradle-api-internal-dynamicobject-prevents-extending-plugin-task/19472/2

Thx for resolution.

**Comment by ysb33r** [comment]
This is not a trivial fix and I expect I can only get around to doing this after 21 July 2017. 

The work is on branch `issue-20` if you would like to tinker with it.

**Comment by ysb33r** [comment]
This should now work with any Gradle 3.x or 4.x.
