### ISSUE TITLE
Support Google repositories

### ISSUE THREAD

**Issue by ysb33r** [ysb33r/ivypot-gradle-plugin#22]

**Comment by omarbelkhodja** [comment]
I'm interested by a solution for this issue...

**Comment by winterDroid** [comment]
Me too

**Comment by ysb33r** [comment]
Does anyone know how Google repositories are handled by Ivy? Knowing this will simplify implementing a solution.

**Comment by ysb33r** [comment]
By looking at the Gradle code, it looks like just creating another Maven repo with URL `https://dl.google.com/dl/android/maven2/`

**Comment by ysb33r** [comment]
@omarbelkhodja @winterDroid I just released 0.7 with support for Google repositories. I hope it works for you.
