### ISSUE TITLE
kotlinx-html-jvm from jcenter causes the plugin to fail

### ISSUE THREAD

**Issue by NikolayMetchev** [ysb33r/ivypot-gradle-plugin#27]
The following build file will cause the error below:

```
plugins {
    id 'org.ysb33r.ivypot' version '0.6'
}
apply plugin: 'java'
syncRemoteRepositories {
    repoRoot 'c:\\temp\\test'
    repositories {
        jcenter()
    }
}

dependencies {
    compile("org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.8")
}
```

`[syncRemoteRepositoriesConfigure] :: Ivy 2.2.0 - 20100923230623 :: http://ant.apache.org/ivy/ ::
[syncRemoteRepositoriesConfigure] :: loading settings :: file = C:\percentile\dev\Scratch\build\tmp\syncRemoteRepositories\ivysettings.xml
[syncRemoteRepositoriesResolve] ivy.instance reference an ivy:settings defined in an other classloader.  An new default one will be used in this project.
[syncRemoteRepositoriesResolve] :: problems summary ::
[syncRemoteRepositoriesResolve] :::: WARNINGS
[syncRemoteRepositoriesResolve]                 module not found: org.jetbrains.kotlin#kotlin-stdlib;${kotlin.version}
[syncRemoteRepositoriesResolve]         ==== BintrayJCenter: tried
[syncRemoteRepositoriesResolve]           https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/${kotlin.version}/kotlin-stdlib-${kotlin.version}.pom
[syncRemoteRepositoriesResolve]           -- artifact org.jetbrains.kotlin#kotlin-stdlib;${kotlin.version}!kotlin-stdlib.jar:
[syncRemoteRepositoriesResolve]           https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/${kotlin.version}/kotlin-stdlib-${kotlin.version}.jar
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
[syncRemoteRepositoriesResolve]                 ::          UNRESOLVED DEPENDENCIES         ::
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
[syncRemoteRepositoriesResolve]                 :: org.jetbrains.kotlin#kotlin-stdlib;${kotlin.version}: not found
[syncRemoteRepositoriesResolve]                 ::::::::::::::::::::::::::::::::::::::::::::::
[syncRemoteRepositoriesResolve]`

**Comment by ysb33r** [comment]
Investigated this with @gijsleussink. This does not seem to be the plugin's fault. Even if one runs `gradle dep` the `kotlin-html-jvm` will not resolve.

The issue seems to be related to the injected `kotlin.version` property which is not available anywhere - not even via the parent POM.

We are not even sure why the JetBrains folks have set it up this way.

**Comment by NikolayMetchev** [comment]
Thanks, we've decided that a better approach to using this plugin is to use a local sanotype nexus repo. 
You can try solving this problem but I thought I'd let you know we no longer are using the plugin. Thanks
