### ISSUE TITLE
No support for dependency classifier

### ISSUE THREAD

**Issue by realPyR3X** [ysb33r/ivypot-gradle-plugin#34]
I'd like to have this plug-in fetch artifacts other than jars. For example the following line causes problems. I am trying to download a zip distribution of apache karaf which is a dependency of my project.

dependencies {
  karaf 'org.apache.karaf:apache-karaf:4.2.2@zip'
}

Output:
[syncRemoteRepositoriesResolve] :::: WARNINGS
[syncRemoteRepositoriesResolve] 		module not found: org.apache.karaf#apache-karaf;4.2.2
[syncRemoteRepositoriesResolve] 	==== MavenRepo: tried
[syncRemoteRepositoriesResolve] 	  http://repo1.maven.org/maven2/org/apache/karaf/apache-karaf/4.2.2/apache-karaf-4.2.2.pom
[syncRemoteRepositoriesResolve] 	  -- artifact org.apache.karaf#apache-karaf;4.2.2!apache-karaf.jar:
[syncRemoteRepositoriesResolve] 	  http://repo1.maven.org/maven2/org/apache/karaf/apache-karaf/4.2.2/apache-karaf-4.2.2.jar
[syncRemoteRepositoriesResolve] 		::::::::::::::::::::::::::::::::::::::::::::::

**Comment by mpnewcomb** [comment]
I thought this plugin would solve my offline problems, but what good is it if it does not honor extensions and just assumes everything is a jar file?

**Comment by ysb33r** [comment]
You are welcome to submit a PR to solve the problem.

**Comment by ysb33r** [comment]
I think I finally found a solution to this problem. Just doing some additional tests. WIll hopefully be in the 0.10 release.
