### ISSUE TITLE
Documentation for Multi-project is out-of-date

### ISSUE THREAD

**Issue by phreed** [ysb33r/ivypot-gradle-plugin#46]
https://github.com/ysb33r/ivypot-gradle-plugin#multi-project-support

A quick check of the  source code indicates that the `offlineRepoDir` variable mentioned in the documentation does not exist in the source code.
```bash
$ grep -R offlineRepoDir *
README.adoc:        offlineRepoDir = "${rootProject.projectDir}/repo"
```
I suspect `repoRoot` may have been what was intended?

**Comment by ysb33r** [comment]
Yes!

A little PR would be appreciated. This plugin does not get a lot of time allocated from my side.

**Comment by ysb33r** [comment]
Documentation updated to hopefully clear up the confusing usage of `project.ext`
